name: "Build release"

on:
  push:
    tags:
      - v*.*.*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Setup Python # This is for the build script
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run build script
        run: |
          export HY_APP_PLATFORMS=$(sed 's/\r$//' platforms.txt | awk '!/^#/ && !/^$/' | paste -sd ",")
          python hyperbole.py build -r

      - name: Generate hashes
        run: |
          for file in build/*; do
            sha256sum $file >> build/hashes.txt
          done

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: build/*

      - name: Publish to API
        run: |
          export HY_API_POST_KEY=${{ secrets.HY2_API_POST_KEY }}
          pip install requests
          python hyperbole.py publish
